name: cliq2
description: "A social video and chat app"
version: 1.0.0+1


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4 # for Supabase integration
  flutter_dotenv: ^5.2.1 # for environment variables
  go_router: ^15.1.1 # for routing
  flutter_riverpod: ^2.6.1 # for state management
  loading_animation_widget: ^1.3.0 # for loading animations
  uuid: ^4.5.1 # for generating unique IDs
  connectivity_plus: ^6.1.4 # for network connectivity
  image_picker: ^1.1.2 # for selecting images
  permission_handler: ^12.0.0+1 # for handling permissions
  agora_rtc_engine: ^6.5.1 # for video calling
  cached_network_image: ^3.4.1 # for caching network images

  audio_waveforms: ^1.3.0 # for audio waveforms
  path_provider: ^2.1.5 # for file system access

  camera: ^0.11.1 # for camera access
  video_player: ^2.9.5 # for video playback
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0 
  



flutter:
  uses-material-design: true
  assets:
    - .env
  